### ISSUE TITLE
Requesting Generation of JSON files for: [traverse-markings] & [warning-signs] images

### ISSUE THREAD

**Issue by JonathanAspeling** [ShailenNaidoo/k53_learners_guide#35]
Just a note here - the file structure of warning-signs differs from the file structure of :

- information-signs
- regulatory-signs
- traffic-signs
- traverse-markings

in that instead of the image assets just being in the main directory as per there name they are in further subdirectories under warning-signs namely:

- direction-signs
- hazard-signs
- layout-signs
- symbolic-signs

Not sure if for the app's purposes each of these should rather be split out from under warning-signs or if we should lump all the assets into the main warning-signs directory?

**Comment by JonathanAspeling** [comment]
Codebridge Tonight :) Hope you're well @ShailenNaidoo ? Just a reminder for when you have a chance :D

**Comment by shailen-naidoo** [comment]
Definitely going to have a look at it tomorrow

**Comment by JonathanAspeling** [comment]
Sorted thanks! Managed to figure out your Node json-generate script! Able to continue :partying_face:
